### ISSUE TITLE
bug(gatsby-source-s3): There was an error in your GraphQL query

### ISSUE THREAD

**Issue by Vacilando** [gatsby-uc/plugins#255] opened 2022-09-21 22:07 UTC
In Gatsby 4.23.0 switched from:
`"@robinmetral/gatsby-source-s3": "^3.0.0",`
to:
`"gatsby-source-s3": "^3.1.2",`

The build (Gatsby Cloud) did not complete, showing error:
> ERROR There was an error in your GraphQL query:
> If you don't expect "allS3Object" to exist on the type "Query" it is most likely a typo. 
> ...

Tried and checked many times, same error.
Eventually had to revert back to `@robinmetral/gatsby-source-s3`.

**Comment by moonmeister** [comment] 2022-09-23 06:29
Hi @Vacilando!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for dropping by the Gatsby UC! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by moonmeister** [comment] 2022-09-23 06:32
Without a reproduction all I can do is guess. My first one would be to know if you ran `gatsby clean` after updating.

**Comment by Vacilando** [comment] 2022-09-23 08:34
Preparing a reproduction is considerable work. I can do it if I hear here that nobody else has issues running the newest gatsby-source-s3 as a replacement for the last @robinmetral/gatsby-source-s3. The old repo is still much more used than the new one. Does the new one actually work? Are there automatic tests that confirm it?

If I see it works for others and my case is isolated, I'll be happy to prepare a reproduction.
For now I consider it a generic bug of gatsby-source-s3.

**Comment by moonmeister** [comment] 2022-09-23 16:56
Yes, the same tests that ran for that version are running on this version and passing.

**Comment by ahansson89** [comment] 2022-10-03 08:48
I get the same error

**Comment by moonmeister** [comment] 2022-10-04 04:41
#262 will be released with #261. Feel free to reopen this if it's not resolved.

**Comment by Vacilando** [comment] 2022-10-04 10:49
Same problem with 3.1.3. - despite gatsby clean and a fresh build.

<img width="754" alt="image" src="https://user-images.githubusercontent.com/147258/193800565-9c876419-ed15-46d3-a771-bdbd1d001f6e.png">

We've had to revert to using the last @robinmetral/gatsby-source-s3 once again.

NB I have no rights to reopen this ticket.

**Comment by moonmeister** [comment] 2022-10-04 17:13
Thanks gents. I just figured out the compiled files were somehow not getting deployed with the build. I know why they weren't, not sure why it just started happening...who knows...maybe it's been like this for a while. Thanks all, next version should be working.

**Closed by moonmeister** 2022-10-04 17:13 UTC
Labels: bug

**Comment by Vacilando** [comment] 2022-10-04 22:09
I confirm that gatsby-source-s3@3.1.4 works fine, thanks for the fix, @moonmeister!
