### ISSUE TITLE
bug(<gatsby-source-strapi>): <"gatsby-source-strapi" threw an error while running the sourceNodes lifecycle>

### ISSUE THREAD

**Issue by soichiro0210** [gatsby-uc/plugins#427] opened 2023-05-08 17:52 UTC
## Describe the bug

I get the following error when building gatsby.
"""The plugin "gatsby-source-strapi" created a node of a type owned by another plugin."""

If I delete the cache and rebuild, it builds correctly, but it does not work with webhook build. Also, I have given ""x-gatsby-cache: false"" to the webhook in the header.

## Error sentence
ERROR "gatsby-source-strapi" threw an error while running the sourceNodes lifecycle:

02:45:46 AM:
The plugin "gatsby-source-strapi" created a node of a type owned by another plugin.

02:45:46 AM:
      The node type "File" is owned by "gatsby-source-filesystem".

02:45:46 AM:
      If you copy and pasted code from elsewhere, you'll need to pick a new type name

02:45:46 AM:
      for your new node(s).

02:45:46 AM:
      The plugin creating the node:

02:45:46 AM:
      {

02:45:46 AM:
    "resolve": "/usr/src/app/www/node_modules/gatsby-source-strapi",

02:45:46 AM:
    "id": "2a4942e6-cd91-5aa5-bdf3-1b39a2db24d6",

02:45:46 AM:
    "name": "gatsby-source-strapi",

02:45:46 AM:
    "version": "3.2.0",

**Comment by moonmeister** [comment] 2023-05-10 00:20
Duplicate of #426

**Closed** 2023-05-10 00:20 UTC
Labels: bug
